(ns lotuc.akka.actor.scaladsl
  (:require
   [potemkin]
   [lotuc.akka.actor.typed.message-and-signals]
   [lotuc.akka.actor.typed.scaladsl.behaviors]
   [lotuc.akka.actor.typed.scaladsl.actor-context]
   [lotuc.akka.actor.typed.scaladsl.timer-scheduler]
   [lotuc.akka.actor.typed.scaladsl.routers]))

(potemkin/import-vars
 [lotuc.akka.actor.typed.scaladsl.behaviors
  setup
  with-stash
  stopped
  receive
  receive-message
  receive-partial
  receive-message-partial
  receive-signal
  intercept
  monitor
  log-messages
  supervise
  with-timers
  with-dynamic-mdc
  with-static-mdc
  with-mdc
  ->behavior]
 [lotuc.akka.actor.typed.scaladsl.actor-context
  self
  system
  log
  set-logger-name
  children
  child
  spawn-anonymous
  spawn
  delegate
  stop
  watch-with
  watch
  unwatch
  set-receive-timeout
  cancel-receive-timeout
  schedule-once
  execution-context
  message-adapter
  ask
  ask-with-status
  pipe-to-self]
 [lotuc.akka.actor.typed.scaladsl.timer-scheduler
  cancel-timer
  cancel-all-timer
  active-timer?
  start-timer]
 [lotuc.akka.actor.typed.scaladsl.routers
  pool-router
  pool-with-pool-size
  pool-with-broadcast-predicate
  pool-with-random-routing
  pool-with-round-robin-routing
  pool-with-consistent-hashing-routing

  group-router
  group-with-random-routing
  group-with-round-robin-routing
  group-with-consistent-hashing-routing])
